<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Example.Payroll.Application\Example.Payroll.Application.csproj" />
    <ProjectReference Include="..\..\Timesheets\Example.Timesheets.Application\Example.Timesheets.Application.csproj" />
  </ItemGroup>
</Project>
