<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Example.Timesheets.Domain\Example.Timesheets.Domain.csproj" />
    <ProjectReference Include="..\..\Kernel\Example.Kernel\Example.Kernel.csproj" />
  </ItemGroup>
</Project>
